services:
    asdoria_pictogram.listener.admin.menu_builder:
        class: Asdoria\SyliusPictogramPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
